# Generated by Django 3.0.7 on 2020-06-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='foo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
    ]
